### ISSUE TITLE
dedicated homepage ? or at least a banner ?

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biologging-sensor-client#104]
From Johan S:
"I think you should have a header like in the ASV-portal. Otherwise you might think that you are at the mainpages of SBDI."

to be discussed @blacksparrowhawk @DeboraArlt 
So far we have decided to have the dataset listing as the homepage.
But we could as well have a dedicated landpage like the ASV portal landpage (see screenshot below)

Another opetion would be to have a small banner in-between the menu and the content, that clearly indicates that this is not an SBDI page but the biologging website. Maybe a shorter one ? Maybe Johan you can provide an image of a radar or something horizontal that could fit ?

The ASV homepage + banner
![Screenshot from 2024-09-09 17-54-41](https://github.com/user-attachments/assets/a26fc58c-28d9-433d-8609-6fbba474b8d7)

**Comment by DeboraArlt** [comment]
I do not think we need a big fat header like this. we can have something similar perhaps on the 'About' page, but not on the others. Check out for example the ASV filter page 
![bild](https://github.com/user-attachments/assets/e7903cf8-a334-46de-81b2-a57de3b1a70f)
-no big fat header here. perhaps could add page headers like they have, for us e.g. "Biologging datasets" and "Biologging data visualisation".
What we more certain should add is something like this in the blue menue bar:
![bild](https://github.com/user-attachments/assets/2fc6e15b-c33b-4055-8cf6-a7a4ba1863f5)
-but with text "SBDI Biologging".

**Comment by DeboraArlt** [comment]
we can discuss this during a Friday meeting

**Comment by mathieuLU** [comment]
has been decided to do this way : 

 - the "About" button of the menu will become "Biologging Portal" and will be the first item of the menu. That ex-About page will become the new landing page.
 - on that new landing page, we will keep all the text from the previous About page and add a couple of things : 
 - a title "Biologging Portal". The font of the title (h1 h2 h3 ?) will be kept for all the different titles of the other pages
 - we will reuse the way the asv-portal organise the buttons on the landing pages with columns:
![Screenshot from 2024-09-13 17-38-11](https://github.com/user-attachments/assets/c169c911-15d9-4fe3-bcd0-fd1bbfbd93cf)
- we'll have 3 buttons : dataset listing, dataset visualisation, api (external link to the swagger page)
- add an image/banner anyway ?
- maybe a bit more appealing :)

**Comment by DeboraArlt** [comment]
"Biologging Portal" - should perhaps be "SBDI Biologging Portal" or "Swedish Biologging Portal" ? As we are not the one and only ;-)

**Comment by DeboraArlt** [comment]
skip image/banner - we don't have one and I cannot easily come up with one. we do'nt want moose (like WRAM), or great snipe (to birdy). we can spend sometime on this later, if we have a good idea. or if we really want some image: does not need to be a logo, perhaos just a banner with a row of oictures of some of the main features organisms? great snipe, moose, some other bird, bear? idaally of those with a tag. but this also will take some time to get those pivtures together. so I still suggest skipping this for now.

**Comment by mathieuLU** [comment]
I updated the homepage. It definitely needs more images/colors I think. 
Feedbacks are welcome @DeboraArlt @blacksparrowhawk 
![Screenshot from 2024-09-17 16-01-32](https://github.com/user-attachments/assets/db913399-01b0-4267-9d06-bff5120b4299)

**Comment by DeboraArlt** [comment]
Yeah, we cannot have a boring webpage ;-)
Easiest for now would be adding photographs. To avoid highlighting one taxon I suggest a "collage" of let's say 3 or 4 organisms. Holger will certainly and happipy be able to contribute with a moose carrying a collar. Åke probbaly can contruíbute with a great snipe carrying a geolocator. Is there an image illustrating the radar tracking somwhow? I think you had something on the old Canmove portal page? I can aks the pear people for a bear with collar given that they will contribute with some data later this year, but this will be quite similar to moose. any other ideas of photos of organisms with instrument that can illustrate te breadth of data/organisms?

**Comment by mathieuLU** [comment]
nicer this way

![Screenshot from 2024-09-19 10-04-28](https://github.com/user-attachments/assets/54920e85-aee2-4cce-bd05-488d2b2acbff)

**Comment by DeboraArlt** [comment]
yes, very good! we'll fix some nice organism photographas later :)

I suggest following texts (not longer though, rather shorter):
Browse our available datasets [without "list"]
Explore the data
Use our API to download data

For the moment I think such short texts are sufficient. I o not really see that the user needs more explanation. it's easy enough to click and have a look.

**Comment by mathieuLU** [comment]
fixed with https://github.com/biodiversitydata-se/biologging-sensor-client/commit/019b0ae871b730cced6070ede9a7fa0cade23a90

i only kept "fetch" instead of download for the API; since it's more accurate ;-)

let me know if we should reopen this issue !

**Comment by DeboraArlt** [comment]
ok, no problem :)
