### ISSUE TITLE
Actogram. embedded legend + text 

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biologging-sensor-client#107]
status of the discussion regarding the view of the actogram

![Screenshot from 2024-09-13 17-46-12](https://github.com/user-attachments/assets/1feb28a9-a4d5-4bd7-8e77-2efafbcd8826)

**Comment by mathieuLU** [comment]
and here is coming some modifications for the legend https://github.com/biodiversitydata-se/biologging-sensor-client/commit/e0e0a17a80aa0a03740cb1d17f1345559a46e693
![Screenshot from 2024-10-11 10-22-02](https://github.com/user-attachments/assets/06f501a9-c302-41ca-9576-b7baa8518012)

**Comment by mathieuLU** [comment]
new version including the legend with taxon/animalId, the left-aligned text, and the frame around the colors for the legend
![Screenshot from 2024-10-11 14-45-16](https://github.com/user-attachments/assets/e223f102-29f0-4b5b-a46f-8f51e78f22ab)

feedbacks are welcome :)

**Comment by DeboraArlt** [comment]
Looks good to me. I suggest to change text to: Activity data for one randomly selected animal (taxon and animal ID in figur legend) showing the first ....

in case someone wonders what 5153166 stands for.

**Comment by mathieuLU** [comment]
fixed with https://github.com/biodiversitydata-se/biologging-sensor-client/commit/33fc4a415334b5d5a92abfa349205341a16134d3

i let you close the issue if it looks good to you !

**Comment by mathieuLU** [comment]
my bad, i should have seen it... fixed!
