### ISSUE TITLE
In the visualisation tab, improve the display when no data 

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biologging-sensor-client#110]
Several questions, when browsing the visualisation page :  
https://biologging.biodiversitydata.se/visualisation/all

- should we list the dataset with accessRights = "restricted access, no view" ? 
they can be easily hidden
if we don't hide them, we should at least write that no data is available for this dataset. So far nothing is displayed, only  a blank block :
![Screenshot from 2024-10-18 10-52-18](https://github.com/user-attachments/assets/ed55c070-6f30-4499-ba36-9e45b34b0386)

 - the text written when no data is available for a specific sensor is quite confusing
 Try for instance the dataset "Tracking Radar Falsterbo Spring 2010-2011". No data is available for the wingbeat sensor, so the page ends up with a strange sentence, event when there is another map displayed before "No visualisation available. Download data for analysis"

![Screenshot from 2024-10-18 10-50-44](https://github.com/user-attachments/assets/86fb5fcc-3dd9-494b-9bb7-209378a1dff1)

any suggestion for the display @DeboraArlt ?

**Comment by DeboraArlt** [comment]
regarding:
should we list the dataset with accessRights = "restricted access, no view" ?
>I think I agree that on the Visualisation page we do not list the completly restricted datasets. this will just be confusing. I vote for hiding them.
It may be still a little confusing for a user that missed the empargo/access info on the dataset listing page, but if the user is missing a dataset on the Vis.page then they can go back to the dataset listing and hopefully discosver the access info.

regarding:
"No visualisation available. Download data for analysis"
>This is for a case where the data are available but we just have not worked on the visualisation. correct?
What about changing the text to "No visualisation for this sensor type provided. Download data for viewing."
Do we think we will work on a visualisation for those sensors, like wingbeat? if we think it's quite likley withing a forseeable time (< some months) then text could be:
"Under development. No visualisation for this sensor type provided yet. Download data for viewing."

**Comment by mathieuLU** [comment]
updated with https://github.com/biodiversitydata-se/biologging-sensor-client/commit/c437eaaf02168187a5c0fb1c37cf42c486c2dbe6

so far we have no dataset with "no open access" so we can't see the difference ;-)

the text is changed as well

the issue can be closed from my point of view

**Comment by DeboraArlt** [comment]
ok
