### ISSUE TITLE
To check if the number of datapoints displayed is accurate

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biologging-sensor-client#88]
coming from jira https://biologging-data-lu.atlassian.net/jira/software/projects/BIOSENSOR/boards/1/backlog?selectedIssue=BIOSENSOR-124

User tested and highlighted that there are 45 data points displayed, not 30.

To do

    Check if the data points displayed are accurate

for instance Dataset visualisation => Moose => temperature. legend is saying "Total number of records is 30" but 45 points

**Comment by mathieuLU** [comment]
wow it took me some time to understand how they did that but now i understand. 
That line under the linegraph "Total number of records is 30" is listing the number of events for one specific dataset

for the great snipe we have 29 results. for the moose dataset we have 32 results.
Then it has been decided to cut to 30 in the code (why ??), here https://github.com/biodiversitydata-se/biologging-sensor-client/blob/fae6250c8a616a244705c9b15a1da4fd4deda8f9/biologging-sensor-data/src/app/visualisation/%5Bid%5D/page.tsx#L32

ANd then, a bit later in the code, it takes only the first 5 lines https://github.com/biodiversitydata-se/biologging-sensor-client/blob/fae6250c8a616a244705c9b15a1da4fd4deda8f9/biologging-sensor-data/src/components/graphs/line/LineGraph.tsx#L111 to display 5 lines.

It has to be reordered.

 - what do we want to display at the end of that graph ? maybe the fact that we display only X event/track/animal/line on the linegraph. Then X should be in the parameters of the project, not in the code
 - slicing to 30 makes no sense i think, it shoulöd be sliced to X, or even better, we should ask only the X first results at the API.
 - for each line, we have up to 100 points. Is that ok ? do we want more/less ?

**Comment by DeboraArlt** [comment]
not sure I understand. "number of records" cannot be number of events as we have defined events. is rather the number of records (measurements) in a tracking event? but this cannot be correct either. Looking at the snipe altimeter graph there are about 85 data points (records, measurements) per animal. So what then is the 29 or 32?

I would want to see a series of measurements, i.e. a series of altitudes (looks like this is what is displayed), or for temperature a series of temperature measurements during a period of time. So x-axis being a time axis, and y shoing the measurement values. showing 5 animals as examples is fine. For me the text line "total numbers of records xx" is not necessary. I can see from the x-axis that this span for example a number of measurement during 4 days (ca, snipe altimeter graph).

For each line up to 100 points seems good to start with. less will show less information, but reading is not difficult with 100 values - so there is no reason to reduce for better readability. More is not necessary either - that would make it more difficult to read details. I think for different data (organisms, sensors, ..) different time periods may be of interest. For example snipes - will be more interesting to see altitude during migration that when they just sit around at the breeding site. or for moose may be more interesting showing body temperature during winter than during summer (perhaps). 
Would also be nice (but we can leave this for later, put in backlog) to be able to make some slection as a user. or having two (or more) versions of the graph, let's say one showing all records from a tracking event - will not be possible to see details but can roughly see how tha measurement vary over the whole tracking event. two - showing a shorter time period showing a typical pattern (pretty much what is shown now).

**Comment by mathieuLU** [comment]
same comment as here https://github.com/biodiversitydata-se/biologging-sensor-client/issues/93#issuecomment-2334221020
