### ISSUE TITLE
To display visually if a filter is applied in the dataset listing

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biologging-sensor-client#90]
from jira https://biologging-data-lu.atlassian.net/jira/software/projects/BIOSENSOR/boards/1/backlog?selectedIssue=BIOSENSOR-133

It is not immediately obvious to users when a filter is applied.

    When a filter is applied:

- make it visible that a filter is applied
- allow user to easily remove the filter

**Comment by mathieuLU** [comment]
The table is filtered with a module calls ag-grid.
its behavior is a bit customizable, and you can select themes, but it's hard to do everything you want.

for instance regarding the way to remove the filters, it's possible to display a "Clear" button to remove a filter in a column.
it looks like that : 
![Screenshot from 2024-08-05 15-17-21](https://github.com/user-attachments/assets/34004702-69e3-452d-a0cc-d47c3fcb187d)

But so far i can't find a way to remove all the filters (maybe not needed). Let me know if it sounds better to you.

Then there is already an icon showing that the column is filtered : 
![Screenshot from 2024-08-05 15-25-58](https://github.com/user-attachments/assets/fb9b9e8b-f23e-4281-85e5-313c3b9ae56f)

but for sure it should be more visible. I can try to put it in red this way. What do you think ?
![Screenshot from 2024-08-05 15-42-10](https://github.com/user-attachments/assets/4a6339d1-17d6-40fb-9399-99198ae50fca)

**Comment by DeboraArlt** [comment]
I think it works like it is now. After I have applied a filter I can now see the symbol you marked red aabove, end when I select the filter function I can see that I currently use a filter. 
So for me this issue can be set as done :)
