### ISSUE TITLE
Maps : add legends

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biologging-sensor-client#92]
from jira https://biologging-data-lu.atlassian.net/jira/software/projects/BIOSENSOR/boards/1/backlog?selectedIssue=BIOSENSOR-127

To add a legend

 - Explain the black circles, expain the points, explain that different coloured tracks refer to different animals – and which (VAS_xxxx, VAS_yyyy, ...).

 - To display values when user mouse over the data points

**Comment by mathieuLU** [comment]
ok so i need more details about how to display these information. 
Do we need a generic text block ? Displayed for all the maps ?
do we want it to be visible all the time ?

Some information are common to all the maps display : 
 - A maximum of 5 tracks is displayed
 - For each track a maximum of 20 points is displayed
 - One track is one animal, and has one colour (actually I discovered
other ?

And then about the legend : 
 - The black dot is the final displayed point of a track 
 - maybe we should display the same kind of legend as for the altimeter/thermometer
 
![Screenshot from 2024-08-08 16-21-42](https://github.com/user-attachments/assets/a47b5b4a-2eb2-4d68-b95f-39ad2407c2a4)

**Comment by DeboraArlt** [comment]
for det legend of things that are always the same I guess we need what you call a generic text block, e.g.:
Map displays a maximum of 5 tracks, each track is from one animal with a maximum of 20 position points displayed. (here comes a follow up question: which tracks? which points? who/what decides which tracks are displayed, and which points (which part of a track?)? maybe don't need to explain in legend but would be good to know if someone asks)
[print black circle] last position (on the WRAM pages for example it shows 
![bild](https://github.com/user-attachments/assets/a889051d-a9b5-47d9-91f1-fe3dc5d7ec2a)

At the moment the figure headers are not very user friendly. I think they display the sensor type or similar, e.g. the map has title "Geographic spherical coordinate system" - I think it would be clerar with a specific image title (or use as subtitle) like e.g. "animal tracks" - with "animal tracks" in the title we do not any specific legend text.
same gors for e.g. the temperature diagram - has now title "thermometer" but more user friendly would be something like "body temperature"? may have to carefully select the title text so it is representative for different types of thermometer sensor data.

For the colours of the different tracks - yes, have the same kind of legend as for altimeter/thermometer. Ideally use the same colours for a track and as the temperature lines if this is data from the same animals (I assume it is).

map mouseover positions: looks good. BUT - is it possible to add also the date and time for the position?
Similar to the temperature diagram: there it is date and time and animal now that is dipslayed at map mouseover, ideally would also be nice to see the exact temperature value.

Let's look at this together during the next meeting.

**Comment by mathieuLU** [comment]
same comment here as what was decided here https://github.com/biodiversitydata-se/biologging-sensor-client/issues/93

of course the mouse over for the map can display date+time !

**Comment by mathieuLU** [comment]
status of the discussion regarding the maps

![Screenshot from 2024-09-13 17-49-38](https://github.com/user-attachments/assets/92d8f420-5db0-4eb8-8202-c716f5ccd070)
![Screenshot from 2024-09-13 17-49-43](https://github.com/user-attachments/assets/9c0df54a-d7aa-4a30-8de6-d2e45f997b33)

**Comment by mathieuLU** [comment]
OMG what a mess it was only to change this tooltip for the map...
quite tough to deal with this Coordinate object and to send extra info to the map (tag id, date, ..)
https://github.com/biodiversitydata-se/biologging-sensor-client/commit/1c5156e6f39add0c841fdea4cb7229899f3d7039 and https://github.com/biodiversitydata-se/biologging-sensor-client/commit/ada0965486ae501006661b87a0e1662f9d586fe3 and 

looks like we have something ok now
![Screenshot from 2024-09-26 14-25-10](https://github.com/user-attachments/assets/c77d97ee-bf5c-420c-b759-16637c6cd8f7)
![Screenshot from 2024-09-26 14-25-32](https://github.com/user-attachments/assets/a3453f38-7f4d-4477-a2ac-bcbc89fe7a09)

the legend is still missing

**Comment by mathieuLU** [comment]
ok so we now have an embedded legend box.
last commit => https://github.com/biodiversitydata-se/biologging-sensor-client/commit/9d0188d7a82256bf94a9553348ae8290a08a2895

it works well to have the text "scientific name + tagID" for the moose project. But unfortunately it does not work for the tracking radar. Since there is no tagID attached to the animal. See the screenshots below

Moose :
![Screenshot from 2024-10-02 11-17-05](https://github.com/user-attachments/assets/8eb42880-2d65-4526-b1ad-ec03ccde5e29)

Tracking radar :
![Screenshot from 2024-10-02 11-17-16](https://github.com/user-attachments/assets/fac71eb7-5619-4bee-a200-4f85cd64ac61)

Since i have the same text without tagID, the legend does not know how to solve it and displays only the first one. Several options :  
 - attaching the animaID instead of the tagID when no unique tagID
 - displaying only the scientificName (but i have to find a way to differentiate the series in the code)

**Comment by DeboraArlt** [comment]
I vote for option 1: attaching the animaID instead of the tagID when no unique tagID

**Comment by mathieuLU** [comment]
done
![Screenshot from 2024-10-08 15-00-16](https://github.com/user-attachments/assets/b8746a12-a170-4004-8d62-6071539fce06)

**Comment by mathieuLU** [comment]
fixed as well with https://github.com/biodiversitydata-se/biologging-sensor-client/commit/68863d19545abc5806d662bb67089838d593c974

**Comment by mathieuLU** [comment]
new legend left-aligned (as well for the embedded) => https://github.com/biodiversitydata-se/biologging-sensor-client/commit/421ad4909486c1c89d3236336da5d8e5405aa39f

![Screenshot from 2024-10-11 14-47-38](https://github.com/user-attachments/assets/5489fdea-5a0b-49ad-bf95-79c9c5ae9f45)

**Comment by mathieuLU** [comment]
Åke made me realize that we have only one legend for the maps, when you suggested 2 different texts. SO right now I always disaply the text you suggested for the tracking radar, even for the moose : https://biologging.biodiversitydata.se/visualisation/dataset_wram_moose_2003

Since this is the same tool, i think it's easier to keep the same text all the time. Is it ok if we use all the time the text you wrote for the moose tracking data ?

**Comment by DeboraArlt** [comment]
I see. We missed that there should be a common text for the maps independent of sensor type. So we need a general text that can cover different sensor types. Right now the texts that I suggested include bits that are specific and mention "radar" pr "GPS". 

suggestion for a new general text, replacing "radar" with "sensor":
Movement data for a random selection of 5 animals (animal IDs in legend). Each trajectory displays the first 50 positions derived from sensor measurements, starting at black circle (sensor deployment). Use mouse over a position to read GPS coordinates, animal ID, date/time.

question - is it the same number of positions (50) we display for GPS and radar? Or can you make this element dynamic?

**Comment by mathieuLU** [comment]
yes we display the same number of position

of course we can configure a different sensor configuration for each if needed.

yes right now it's the same number of positions for any map item

**Comment by DeboraArlt** [comment]
and regarding the display of data for the data points in the map:
I realise that the decimals shown for Lat/Lon seem to be the same as what is contained in the database. Is there an easy way to limit the number of decimals shown in the labels, to lets say 4 or decimals?

This is how it looks for snipe now:
![bild](https://github.com/user-attachments/assets/1542b2be-0734-458b-999d-21f35156f81d)
=5 decimals, looks ok

moose:
![bild](https://github.com/user-attachments/assets/a84225e3-ae5f-4fe8-afbb-3e8be2ce0cce)
=7decimals, ok-ish, starts to get a bit much

radar:
![bild](https://github.com/user-attachments/assets/eb83ef6b-5e18-4862-84ca-181f7bfb1afa)
=10+ decimals, hard to read

This is more for readability, simlar as the suggestion to change to a more readable date-time format. can be done after launch if time is limiting.

**Comment by mathieuLU** [comment]
yes !
fixed with https://github.com/biodiversitydata-se/biologging-sensor-client/commit/76b6554f1cb4a39f0abc9b2680a57e834147a30e and https://github.com/biodiversitydata-se/biologging-sensor-client/commit/913bfdf841764cfae77a030c0edf624a71be1817

**Comment by DeboraArlt** [comment]
let's keep it simple for now, the text works for any "sensor" :)  We can always get more dynamic later ;-)

nice decimal fix :)

can be closed :)
