### ISSUE TITLE
Change "elk" to "moose"

### ISSUE THREAD

**Issue by DeboraArlt** [biodiversitydata-se/biologging-sensor-client#96]
The Latin name, Alces alces, is known as "moose" in North America and älg (elk) in Sweden. But "elk" in North America is a deer-like animal otherwise known as a "Wapiti"
https://naturetravels.wordpress.com/2007/10/29/whats-the-difference-between-a-moose-and-an-elk/

‘elk’ would normally be correct to use for ‘älg’ in Sweden, but to avoid confusion internationally/globally it’s better to use ‘moose’ because in America ‘elk’ is a species of deer.
'Moose' is also what the data creators call the species (in publications etc.), and have called like this in WRAM since the start of WRAM.
Seems like this in Norway and Finland too - the reserachers call the species moose in publications.

So we should change elk -> moose, to avoid confusion and keep the name used by the project in Sweden.

**Comment by mathieuLU** [comment]
I do not know exactly how to process here.
I get the information from https://species.biodiversitydata.se, by providing a scientificName or a guid. So I send "Alces alces" and i get this 
https://www.gbif.org/species/2440940
https://species.biodiversitydata.se/ws/search.json?q=2440940
which a the commonNameSingle = Elk

do you know which element of the gbif taxonomic backbone we could use ?

if not i will just force the name to be Moose ;-)

**Comment by DeboraArlt** [comment]
Hm, don't know. 

Following https://species.biodiversitydata.se/ws/search.json?q=2440940 I can see that there is a long list of possible Commonnames, one of them is moose. Can you make it select this one? force it?

Or about make it using a particular part of the backbone?
When I look at Cataloge of Life which is highest up in the GBIF backbone I get https://www.gbif.org/species/219031150 and there they have 3 listings for vernacular names: elk, moose, original (I think the last one is some kind of wrong entry that get's picked up). would also need some forcing to use 'moose'.

let's talk about it during the next meeting.

**Comment by mathieuLU** [comment]
i went for the easiest way : forcing it ;-)
